spring:
  application:
    name: booking-history-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:7432/booking_history}
    username: ${SPRING_DATASOURCE_USERNAME:booking_history}
    password: ${SPRING_DATASOURCE_PASSWORD:booking_history}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: ru.spomprt.bookinghistoryservice.dto

kafka:
  topic:
    booking-created: ${KAFKA_TOPIC_BOOKING_CREATED:booking-created}

logging:
  level:
    ru:
      spomprt:
        bookinghistoryservice: DEBUG
    org:
      springframework:
        kafka: DEBUG
